### PR TITLE
Rename internal obsolete references

### PR DESCRIPTION
**Pull request by david-christiansen**

### CODE REVIEW

**Comment by jonsterling** [comment]
thanks! I'll see what travis does 😜

**Comment by david-christiansen** [comment]
It will fail, but we'll discover our version bounds.

**Comment by jonsterling** [comment]
OK, now I think among other things, it is looking for a `main.rkt` file. But I'm not sure.

**Comment by david-christiansen** [comment]
Probably ought to squash this when merging...

**Pull request merged**
